-- exploratory Data Analysis

-- 1. Total Revenue

select sum(revenue) total_revenue
from sales_data;

-- 2. the product with the highest revenue

select product,sum(revenue) as total_revenue
from sales_data
group by product
order by total_revenue desc
limit 1
;

-- 4. average price of products

select product,avg(price) as average_price
from sales_data
group by product;

-- 5.the category with the highest revenue
select category,sum(revenue) as total_revenue
from sales_data
group by category
order by total_revenue desc
limit 1;

-- 6. average revenue per sale

select avg(revenue) average_revenue_per_sale
from sales_data;

-- 7 revenue generated by yearly quarters

select quarter(`date`) `quarter`,sum(revenue) revenue
from sales_data
group by `quarter`
order by revenue desc;